version: '3.3'

networks:
   aw-network:
      driver: bridge

volumes:
   prometheus_data:
   grafana_data:

services:
  
   prometheus:
      image: prom/prometheus:latest
      container_name: prometheus_inventario_spring
      volumes:
        - ./configuracao-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  #connectando com o container
        - prometheus_data:/prometheus   #armazenar os dados 
      networks:
         - aw-network
      ports: 
        - 9090:9090   
   grafana:
      image: grafana/grafana:latest
      container_name: grafana_inventario_spring
      ports:
        - 3000:3000
      networks:
        - aw-network    
         