global:
  scrape_interval: 5s


scrape_configs:
   - job_name: "api-inventario-spring"
     metrics_path: "/actuator/prometheus"
     static_configs:
        - targets: ["host.docker.internal:8084"]
          labels:
             application: "api-inventario"